### ISSUE TITLE
Enum in high-level Schema should be slice of any

### ISSUE THREAD

**Issue by travisnewhouse** [pb33f/libopenapi#1]
JSON Schema specification states that value in the `enum` array [can be any type](https://json-schema.org/draft/2020-12/json-schema-validation.html#section-6.1.2).  Field [`Enum` in high-level `Schema`](https://github.com/pb33f/libopenapi/blob/54316b4a00046c57779326b70009fc3fa148f426/datamodel/high/base/schema.go#L72) should have type `[]any` in order to contain any possible value from a schema definition.

**Comment by daveshanley** [comment]
I agree. This is an oversight on my part. I will take care of this.

**Comment by daveshanley** [comment]
This has been resolved in v0.1.8. Enums in the Schema is now untyped. Thank you for your contribution, Travis!
