### ISSUE TITLE
v3.Document.Render will always return yaml even when input was json

### ISSUE THREAD

**Issue by TristanSpeakEasy** [pb33f/libopenapi#105]
Would be great to somehow retain the type of the original document when rendering out a document using the `Render()` method.

Either as some state stored in the document that makes the right choice automatically on render or allowing an option to chose output type in the Render method, though if using the option it would then also be good to have a way to tell what format the document was originally ie json or yaml

**Comment by daveshanley** [comment]
I don't think this is very hard to fix (at the document level) it will be a big lift however to go in an add the option to every renderable object (which is all of them). 

We can add the JSON intelligence at the document level however.

**Comment by TristanSpeakEasy** [comment]
I think this makes more sense for the document level render as I see the object level options as being great for generating snippets and things like that which look better in YAML then JSON IMO but I also honestly believe most people will render the entire document more than individual parts

**Comment by daveshanley** [comment]
@TristanSpeakEasy Can you verify this now works as you expect?

**Comment by TristanSpeakEasy** [comment]
Sorry this is fixed
