### ISSUE TITLE
Rendered out yaml doesn't retain style of original document

### ISSUE THREAD

**Issue by TristanSpeakEasy** [pb33f/libopenapi#106]
For example if the original document was using 2 spaces for indentation, the output is using 4 spaces.

Or if the original document was using `'` characters for string delimination, the output is using `"`

I know this might not be particular easy with the yaml library being used but I think its important to support if the library supports mutation in such a way that it is trying to retain the structure of the original document when adding new items etc

**Comment by daveshanley** [comment]
I was wondering when this would pop up. I left everything as default to start - however there are some options.

There are some controls over thinks like quotes for sure. The spacing however I haven't seen anything yet in the library that allows control over that. I don't see it recorded anywhere in the `Node` API either.

The spacing may be a hard no, I can look more - but after working with the lib for a year, I have never come across it. But quoting yes, that is retained n the node API and can be used by the `NodeBuilder` that assembles the objects into a tree.

**Comment by daveshanley** [comment]
Perhaps this can be determined by looking at the whitespace of the original spec. I will have a think on this.

**Comment by daveshanley** [comment]
@TristanSpeakEasy Can you verify this is now corrected? It was added a few versions back.

**Comment by daveshanley** [comment]
@TristanSpeakEasy ping

**Comment by TristanSpeakEasy** [comment]
Apologies, I’m currently on holiday so won’t be able to take a look at this for a little while, feel free to close it and I can reopen if necessary
