### ISSUE TITLE
v3.Operation.Security will be nil when "security": [] defined in schema

### ISSUE THREAD

**Issue by anuraagnalluri** [pb33f/libopenapi#111]
This probably results in a correct `v3.Document` as per the OAS, but it makes it difficult to use this struct to distinguish between "security not defined" vs. "no security" at the operation level.

As per the spec, we should be able to define a global security and use `security: []` as an operation override to specify that a particular method does not require security. However, since `v3.Operation.Security` will be `nil` in this case, it could also correspond to the scenario where security is defined globally but not for the operation.

Wondering if it'd be possible to surface the distinction between `security: []` being defined at the operation level vs. not being defined at all. This would help our tooling know for a given method whether to use global security (if it exists) or no security. Also open to any suggestions you may have regarding a better way to capture this distinction in case I missed it.

**Comment by daveshanley** [comment]
Hi, I'd like to help, but I am struggling to understand this.

Could you write some code that shows how you use the model today, and how you would *like* to use the model to determine security state?

Otherwise without more data, I'm a little lost.

**Comment by daveshanley** [comment]
This helps a lot, thank you. I have a better idea of what you're looking for now.

**Comment by daveshanley** [comment]
This has been fixed and available since `v0.9.0`
