### ISSUE TITLE
Incorrectly failing validation for a circular reference?

### ISSUE THREAD

**Issue by ndimares** [pb33f/libopenapi#113]
Hi @daveshanley,
A [Corner case](https://github.com/speakeasy-api/product-resources/issues/16) brought in by a Speakeasy user. They have modified the Apache Airflow API and are generating clients for it. They [want to define a recursive data structure](https://github.com/speakeasy-api/product-resources/issues/16), but it's tripping a [validation from libopenapi ](https://pb33f.io/libopenapi/circular-references/)(I think).

I actually feel like this should be valid? In this example the children data structure is required but it uses an Anyof, so the circular reference shouldn't be infinite?

**Comment by daveshanley** [comment]
I will have a look asap and see what's up. I haven't looked at the spec/issue yet but just off the top of my head, there are two types of error for circular errors, one is a notification that you have a circle, the other is a bit is set to mark a reference as a infinite loop. This is. Recursive structure that is required but loops indefinitely.

Check the infinite loop bit first to see if it's a genuinely broken loop, or it's it's just letting you know a circle has been found, but it's not a required prop, so it can be allowed to fail.

**Comment by ndimares** [comment]
@daveshanley so I think the issue here is that the required prop is being used, but I actually think the circular reference is valid because it's a tree-like structure where either another tree or a value can be contained.  Basically I think there needs to be subrule to your, "no required circular references *unless an anyOf is being used".

**Comment by daveshanley** [comment]
I haven't been able to look into this yet, i'm on vacation and I'm not looking at code for another week or so. 

AnyOf was a design mistake in my opinion, it creates more chaos than it solves. 

Back online in a week or so.

**Comment by ndimares** [comment]
Also, @TristanSpeakEasy pointed out to me that oneOf rather than anyOf should be used in this scenario. However, I did a quick test and confirmed that the same validation error pops up when you use OneOf.

**Comment by daveshanley** [comment]
This is now configurable from `v0.11.0`: https://github.com/pb33f/libopenapi/pull/173
