### ISSUE TITLE
Maximum and Minimum should be *float64

### ISSUE THREAD

**Issue by thrawn01** [pb33f/libopenapi#121]
I think the `Maximum` and `Minimum` values in `base.Schema` should be `float64`. As defined now it's impossible to define a float64 (aka number) as these values. 

[JSON Schema](https://datatracker.ietf.org/doc/html/draft-bhutton-json-schema-validation-00#section-6.2.2) defines these as `number` which probably means we need to represent them as `*float64` in golang structs.

**Comment by daveshanley** [comment]
Available in `v0.9.0`
