### ISSUE TITLE
base.License missing `identifier` field in OpenAPI 3.1 documents

### ISSUE THREAD

**Issue by TristanSpeakEasy** [pb33f/libopenapi#124]
https://spec.openapis.org/oas/latest.html#fixed-fields-2

According to the Spec in OpenAPI 3.1 documents there should be an `identifier` field of type string.

The `url` and `identifier` fields are mutually exclusive in case there is any validation that needs to be updated around this when added

**Comment by daveshanley** [comment]
Nice catch. Will fix.

**Comment by daveshanley** [comment]
Fixed in `v0.9.0`
