### ISSUE TITLE
Remote reference from authenticated source

### ISSUE THREAD

**Issue by FedeBev** [pb33f/libopenapi#132]
I'm working with private github repositories and I have to resolve a reference to a private file. Is there a way to set headers to the http client that will download the file? Or any other way to resolve a reference from a source that requires authentication.

Just to give an example, this simple curl works for github

```shell
curl -H 'Authorization: token <my_github_pat>' -H 'Accept: application/vnd.github.v3.raw' -O -L https://raw.githubusercontent.com/company/private-repo/branch/swagger.yaml
```

Thanks!

**Comment by FedeBev** [comment]
Thank you @daveshanley!

I proposed a super simple solution in #133  that can be considered a temporary workaround if you have a better plan already in place

**Comment by daveshanley** [comment]
Added in `v0.9.2`
