### ISSUE TITLE
Is it possible to load a resolved schema having the properties instead of $ref?

### ISSUE THREAD

**Issue by nevesgustavo** [pb33f/libopenapi#134]
Hi Team,

We're using your library and working in a feature where we need to read a swagger/openapi specification file find an operation inside a path and return the json schema from a method Get for example. We noticed that there is a Render method inside the schema like this `v3Model.Model.Components.Schemas["WebhookResponse"].Schema().Render()` but we would like to have the resolved schema when exists references, is it possible?

Details:
For testings purposes we are using this [asana.yaml](https://github.com/pb33f/libopenapi/blob/main/test_specs/asana.yaml) spec and we want to have the schema below resolved:

<img width="1417" alt="image" src="https://github.com/pb33f/libopenapi/assets/10534124/9fa5a7be-ebec-4f53-a83d-239e6c2d4f56">

And we would like a result like in the swagger editor below:

<img width="730" alt="image" src="https://github.com/pb33f/libopenapi/assets/10534124/2ce786e2-cf37-4237-a311-71c848e2848d">

Best Regards,
Gustavo Neves

**Comment by daveshanley** [comment]
Hi, 

Did you try `RenderInline` instead of `Render`?

https://github.com/pb33f/libopenapi/blob/main/datamodel/high/base/schema.go#L488

**Comment by nevesgustavo** [comment]
Hi @daveshanley thanks for the reply, that's great using the `RenderInline` I have the resolved schema 👍.

Let me ask you one more question please:
1 - Using this piece of code we have the resolved schema `v3Model.Model.Components.Schemas["WebhookResponse"].Schema().RenderInline()`

2 - But we would like to have the resolved schema inside of a response operation like this
`v3Model.Model.Paths.PathItems["/webhooks"].Get.Responses.Codes["200"].Content["application/json"].Schema.Render()`

and this .Render above returns:
`yml
properties:
    data:
        items:
            $ref: '#/components/schemas/WebhookResponse'
        type: array
type: object
`

Could you please give me a tip on how to relate the Schema $ref with the `v3Model.Model.Components.Schemas` or how to have the resolved schema inside the operation response code?

Thanks in advance.

**Comment by daveshanley** [comment]
Does `v3Model.Model.Paths.PathItems["/webhooks"].Get.Responses.Codes["200"].Content["application/json"].Schema.Schema().RenderInline()` not work?

**Comment by daveshanley** [comment]
Just so you have a mental model, `Schema` is a fully recursive structure, as is `SchemaProxy`. The proxy holds the schema un-built until you call `Schema()` to build the schema, which them recursively jumps constructs the next level down.

If you can render one schema inline, you can render **any** schema inline. 

https://pb33f.io/libopenapi/model/

**Comment by nevesgustavo** [comment]
That's awesome @daveshanley, you are right there is a `RenderInline` inside the schema and this works jus fine.

Thank you very much for your help.
