### ISSUE TITLE
Internal compiler error while testing

### ISSUE THREAD

**Issue by KarineAyrs** [pb33f/libopenapi#144]
When I run tests appears error:
```
# github.com/pb33f/libopenapi/datamodel/low/v2
<autogenerated>:1: internal compiler error: dictionary for ValueReference[go.shape.*"".Response_0].GenerateMapKey should only use concrete types: go.shape.*"".Response_0
```

**Comment by daveshanley** [comment]
What version of go are you using?

**Comment by daveshanley** [comment]
libopenapi requires go `1.18`+ to operate. It's most likely you're running an older version of golang.

To see the tests passing in the pipeline: https://github.com/pb33f/libopenapi/actions/workflows/build.yaml

If the tests pass there, then there is no issue with them and it's a local environment issue.

**Comment by daveshanley** [comment]
What command are you

**Comment by KarineAyrs** [comment]
The problem was really in the environment, so I fixed it and now everything works . Thank you for your time and attention, I think the issue can be closed.
