### ISSUE TITLE
unevaluatedProperties as implemented is causing nil pointer panics...

### ISSUE THREAD

**Issue by jasonquigleyhpecom** [pb33f/libopenapi#145]
Hello!

I am trying to validate a payload against this test schema:

```
openapi: 3.1.0
info:
  title: Burgers
  license:
    name: License Agreement
    url: https://www.example.com/licensing.html
  version: latest
  description: |
    More burgers!
    A unified API for consuming burgers 
  contact:
    name: Ronald Macdonald
    email: burgers@example.com
servers:
  - url: https://api.example.com
    description: Development environment
paths:
  /burgers/create-burger:
    post:
      operationId: createBurger
      requestBody:
        content:
          application/json:
            schema:
              unevaluatedProperties: false
              type: object
              properties:
                name:
                  type: string
                patties:
                  type: integer
                vegetarian:
                  type: boolean
            examples:
              pbjBurger:
                summary: A horrible, nutty, sticky mess.
                value:
                  name: Peanut And Jelly
                  patties: 3
                  vegetarian: true
```

using this:

```
v := schema.NewSchemaValidator()
valid, verrors := v.ValidateSchemaBytes(sch.Schema(), payloadBytes)
```

I get a nil pointer panic. I tested the schema with `vacuum` and it also panics. When I remove the `unevaluatedProperties` line from the schema, it validates with the above code and with `vacuum`.

According to the JSON Schema spec (https://json-schema.org/understanding-json-schema/reference/object.html#unevaluated-properties), `unevaluatedProperties` is just a bool switch which defaults to true. I can't see any conceivable reason to treat it as a schema. Am I reading this wrong?

Additionally the JSON Schema test suite only ever uses a bool:
https://github.com/json-schema-org/JSON-Schema-Test-Suite/blob/b069ac352c3dc1fae71f6f177dafe97001c97920/tests/draft-next/unevaluatedProperties.json

**Comment by jasonquigleyhpecom** [comment]
I went through the test suite some more and now I can see why `unevaluatedProperties` can be a schema. I can't find documentation backing it up.

**Comment by daveshanley** [comment]
Hi, 

So this relates to this issue: https://github.com/pb33f/libopenapi/issues/118

There is a bug in the library for sure, it should not panic - however it's also flexible to be able to cope with either a bool or a schema.

**Comment by daveshanley** [comment]
Would you be able to re-try your code?

**Comment by daveshanley** [comment]
I cannot re-create this issue after the patch. closing.

**Comment by jasonquigleyhpecom** [comment]
Hi @daveshanley!

I can verify that it works now. Thanks very much!
