### ISSUE TITLE
examples with object property called 'properties' included in GetAllSchemas

### ISSUE THREAD

**Issue by 2ynn** [pb33f/libopenapi#160]
When an object property is called `properties` and examples are included, some index references are picked up by `GetAllSchemas()` despite being examples and not schemas.

### Example
```
paths:
  /test:
    get:
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Object"
              examples:
                Example1:
                  value:
                    properties:
                      name: not a schema
                Example2:
                  value:
                    properties:
                      name: another one
components:
  schemas:
    Object:
      type: object
      properties:
        properties:
          type: object
          properties:
            name:
              type: string
      example:
        properties:
          name: not a schema
```

These index references are part of the output of `GetAllSchemas()`:
```
[22] $.paths./test.get.responses.200.content.examples.Example1.value.properties.name
[26] $.paths./test.get.responses.200.content.examples.Example2.value.properties.name
[39] $.components.schemas.Object.example.properties.name
```

Note that the same issue occurs with `x-example` and `x-examples`, ideally the solution would not rely on excluding the specific keywords `example` and `examples`.

**Comment by daveshanley** [comment]
This is a tough one, the indexer does not currently keep a track of what it has seen before, it know knows what it is looking at right now in terms of a node. To make this work, we need a 'memory', like the one used by the resolver when stitching together documents or locating circular references.

**Comment by TristanSpeakEasy** [comment]
@daveshanley would the latest Rolodex fix this?

**Comment by TristanSpeakEasy** [comment]
@daveshanley just a bump on this one as we have a workaround that is a bit of a pain to maintain

**Comment by daveshanley** [comment]
There may be a way to use the node path that is collected by the index to do this. I will circle back on this soon.

**Comment by daveshanley** [comment]
This has been added in `v0.15.6`. 

The new logic will ignore any properties that have a 'example' or 'examples' parent node in the journey, or any kind of extension prefix (`x-`)

Here is a test added for this usecase: 

https://github.com/pb33f/libopenapi/blob/v0.15.6/index/spec_index_test.go#L1654
