### ISSUE TITLE
Outdated doc ?

### ISSUE THREAD

**Issue by oliviernguyenquoc** [pb33f/libopenapi#168]
In this doc, there is this code:
```go
config := index.SpecIndexConfig{
    FollowRemoteRefs: true,
    FollowLocalRefs: true,
}
```
[SpecIndexConfig](https://github.com/pb33f/libopenapi/blob/86f5f3e7cdf0152c417380dedfff15efbf9b956b/index/index_model.go#L50) doesn't seems to have FollowRemoteRefs and FollowLocalRefs in its struct

**Comment by daveshanley** [comment]
This is wrong, this was a suggested design, but was altered after implementation to be less obscure, where in the docs did you find this? it should be corrected.

The values you're looking for are:

```go
AllowRemoteLookup bool // Allow remote lookups for references. Defaults to false
AllowFileLookup   bool // Allow file lookups for references. Defaults to false
```

https://github.com/pb33f/libopenapi/blob/main/index/index_model.go#L93

**Comment by oliviernguyenquoc** [comment]
Just there: https://pb33f.io/libopenapi/the-index/#creating-an-index-from-scratch (multiple times in this section)

Happy to help ;)

**Comment by daveshanley** [comment]
Oh dear, yes the docs are totally wrong! Thank you for your help. I have updated the broken docs.

Thats my bad, I wrote the docs during the design phase of the feature, vs after.
