### ISSUE TITLE
Is SchemaChanges working correctly?

### ISSUE THREAD

**Issue by rschooley** [pb33f/libopenapi#170]
I am using `CompareDocuments` where the properties of a schema have changed:

Original:
```
...
"properties": {
  "id": {
    "type": "integer",
      "format": "int64"
    },
    "name": {
      "type": "string"
    },
    "tag": {
      "type": "string"
    }
  }
}
```

New
```
...
"properties": {
  "id": {
    "type": "integer",
    "format": "int64"
  },
  "name": {
    "type": "integer",
    "format": "int64"
  },
  "foo": {
    "type": "string"
  }
}
```

Using these functions:
```
changes, _ := libopenapi.CompareDocuments(document, document2)
schemaChanges := changes.ComponentsChanges.SchemaChanges
```

The results of the changes are:

| ChangeType | Original | New |
| --- | :---: | :--- |
| ObjectAdded   |       | foo |
| ObjectRemoved | id    |  |
| ObjectAdded   |      | id |
| ObjectRemoved | name  |  |
| ObjectAdded   |       | name |
| ObjectRemoved | tag   |  |

These are the results I would expect:

| ChangeType | Original | New |
| --- | :---: | :--- |
| ObjectRemoved | tag   |  |
| ObjectAdded   |       | foo |
| Modified | name | name |

Version:
github.com/pb33f/libopenapi v0.10.3

**Comment by daveshanley** [comment]
Looking into this for you!

Also, thank you for your donation! I really appreciate it.

**Comment by daveshanley** [comment]
You're correct, there was an edge case (that you discovered) where the logic was getting a bit confused when performing a property swap (as the compiler sees it) which changes the sorting order of the original keys.

In version `v0.10.5` This should be resolved, and the correct output should be:

| ChangeType | Original | New |
| --- | :---: | :--- |
| ObjectAdded   |       | foo |
| ObjectRemoved | tag    |  |
| Modified (name / type)  | string    | integer  |
| PropertyAdded  (name / format) |  |  int64|
