### ISSUE TITLE
Const changes aren't correctly detected in what-changed 

### ISSUE THREAD

**Issue by srir** [pb33f/libopenapi#178]
(as described in https://github.com/pb33f/openapi-changes/issues/67)

We're trying to use `openapi-changes` to detect breaking spec changes to our production API. 

We're not seeing changes to `const` values detected at all (let alone as "breaking"). I've put together a MWE to demonstrate the issue we're seeing (https://gist.github.com/srir/8513874d960a2fd5fbb380f484e4ffc0)

Expected:
- `openapi-changes summary spec_prod.json spec_new.json` detects and reports a difference
- note: the difference is subtle (a change to the `const` value in the `type` property for each of `ResourceNotFoundError` and `FeatureNotAvailableError`)

Actual:
- no differences are detected; `openapi-changes summary spec_prod.json spec_new.json` exits with the following, and exit code `0`:
```
openapi-changes version: 0.0.42 | compiled: 2023-09-09T15:03:00Z


 INFO  printing summary
```

**Comment by daveshanley** [comment]
Will be fixed in next round of updates. Thank you for reporting this.

**Comment by daveshanley** [comment]
Hello, 

I looked through the code, and `const` is correctly handled, so I was curious as to what could be going on. 

I loaded up the examples you provided in the gist and ran them through `libopenapi`

I used this code

```go
package main

import (
	"fmt"
	"github.com/pb33f/libopenapi"
	"os"
)

func main() {

	left, _ := os.ReadFile("const-changes/orig.json")
	right, _ := os.ReadFile("const-changes/new.json")
	if left == nil && right == nil {
		panic("no files found")
	}

	leftDoc, _ := libopenapi.NewDocument(left)
	rightDoc, _ := libopenapi.NewDocument(right)

	changes, errs := libopenapi.CompareDocuments(leftDoc, rightDoc)

	if len(errs) > 0 {
		for _, err := range errs {
			println(fmt.Printf("error: %s:", err.Error()))
		}
	}

	fmt.Println(changes.TotalBreakingChanges())
}
```

It prints out `2`

And when I inspect the changes, I see this: 
![Screenshot 2023-10-06 at 12 20 05 PM](https://github.com/pb33f/libopenapi/assets/187345/67eb8846-cc1b-4bd2-b230-2578a5bd6ecd)

The changes are there, where they should be.

Am I missing something?
