### ISSUE TITLE
PathItem change objects for operations do not include the new object in case of "PropertyAdded"

### ISSUE THREAD

**Issue by sebkunz** [pb33f/libopenapi#186]
Hi!

During my testing I think I found another bug with the operation changes in path items when the property is only present in the `rPath` (change type = "PropertyAdded").

For me the newObject parameter in `CreateChange(changes, PropertyAdded, v3.GetLabel, nil, rPath.Get.ValueNode, false, nil, lPath.Get.Value)` should be set as `rPath.Get.Value` instead of `lPath.Get.Value` since the change object should include the new value instead of the non existent old value from `lPath`. 

Is my assumption correct?

**Example:**
https://github.com/pb33f/libopenapi/blob/4dc693a3f513d134c5b34ecd40b01edb6b63c906/what-changed/model/path_item.go#L236-L238

This parameter is set from the `lPath` for all "property added" operation cases and is set in both swagger and openAPI comparison funcs.

**Comment by daveshanley** [comment]
You are right! this is wrong. This has been fixed in #187

**Comment by daveshanley** [comment]
Fixed in `v0.13.0`
