### ISSUE TITLE
Feature Request: Provide High Level Access to Map of PathItem Operations

### ISSUE THREAD

**Issue by TristanSpeakEasy** [pb33f/libopenapi#19]
Would be great if a v3.PathItem allowed iterating through each of the operations it contains. Currently I will need to have an awkward set of 'if` clauses to evaluate each of the valid operations in the document for a particular path.

**Comment by daveshanley** [comment]
What kind of a signature would you like to see? `GetOperations() map[string]*Operation` or something else?

**Comment by TristanSpeakEasy** [comment]
Yeah map[string]*Operation would be perfect

**Comment by daveshanley** [comment]
Added this in `v0.2.7` 

Thank you for the suggestion!
