### ISSUE TITLE
bug: index out of range if I have a property called oneof in request

### ISSUE THREAD

**Issue by wd345901051** [pb33f/libopenapi#217]
![Snipaste_2023-12-13_15-06-39](https://github.com/pb33f/libopenapi/assets/83993083/51744179-e50e-4c04-93cd-8757082c6ddd)
and this is my yam:
![Snipaste_2023-12-13_15-08-52](https://github.com/pb33f/libopenapi/assets/83993083/0827d218-e405-43dc-88d0-ced9c898212b)
this is my problems? because I used "oneof" as my property name?
But in SwaggerEditor, it is correctly used as a property.

**Comment by daveshanley** [comment]
A resolution for this was added in `v0.15.0` It won't give an out of index error anymore

https://github.com/pb33f/libopenapi/blob/main/index/resolver.go#L640

**Comment by wd345901051** [comment]
thank you. @daveshanley
