### ISSUE TITLE
Diff : wrong management of $ref comparison 

### ISSUE THREAD

**Issue by LasneF** [pb33f/libopenapi#218]
given the test below

last one for today  ; 
```
    left := `openapi: 3.0
components:
  schemas:
    Yo:
      type: int
    OK:
      $ref: '#/components/schemas/Yo'`

    right := `openapi: 3.0
components:
  schemas:
    Yo:
      type: int
    OK:
      type: int'`
``` 
is set as breaking whereas to me should not  

an approach would be to manage the diff after resolving the $ref so that it compares consistant definitive data
this would also match the refactoring use case where some item are moved , factorized and so on

**Comment by daveshanley** [comment]
This has been resolved in `v0.15.0`

Test cases can be found here: https://github.com/pb33f/libopenapi/blob/main/what-changed/model/schema_test.go#L2861
