### ISSUE TITLE
Server Model missing extensions

### ISSUE THREAD

**Issue by TristanSpeakEasy** [pb33f/libopenapi#22]
We are using extensions in the server object which I can't access through libopenapi. 

The spec states `This object MAY be extended with [Specification Extensions](https://spec.openapis.org/oas/v3.0.3#specificationExtensions).` https://spec.openapis.org/oas/v3.0.3#server-object.

We use a number of extensions in various places, I haven't yet got far enough along in our integration to identify where else access to extensions may be missing, but the Swagger documentation is actually incorrect in regards to the various places extensions are supported for example https://swagger.io/docs/specification/openapi-extensions/ doesn't show that extensions can be supported by the server object but the official documentation does

**Comment by daveshanley** [comment]
Thanks for finding this. I did follow the smartbear specs at times when I needed a lookup, I know I missed a few extension points in places where the docs were wrong. 

I'm adding in extensions to `Server` and it will be available shortly.

**Comment by daveshanley** [comment]
This has been fixed in `v.0.3.0`.

Thanks once again for helping make this a better library.
