### ISSUE TITLE
$ref failing to resolve with external file available in the file system in on Windows 

### ISSUE THREAD

**Issue by LasneF** [pb33f/libopenapi#226]
with the  

give an file in the current directory containing this  , given 2 files in a child directory called path 
paths:
  /quote-requests:
    $ref: ./paths/quoteRequests.yaml
  /quote-requests/{id}:
    $ref: paths/quoteRequests@{id}.yaml

neither use case one or 2 works  , it gives 2 differents errors

ERROR cannot locate file in the rolodex, check specification references and base path file: D:\code\repos\developer-portal\documentations\eden\paths\quoteRequests@{id}.yaml

ERROR unable to locate reference anywhere in the rolodex reference: D:\code\repos\developer-portal\documentations\eden\paths\quoteRequests.yaml

**Comment by daveshanley** [comment]
`paths/quoteRequests@{id}.yaml` is not valid, It will never work. 

However the the other one is valid. The rolodex code has been beaten to death recently as it was a complete re-build of the entire lookup system. It's much more powerful now and also much more complex.

There are multiple ways to use it and the index, some of the configuration options you have used may need adjusting. 

Can you paste the code you're using to create a document from the OpenAPI spec? Unless you're using the rolodex directly (docs are here: https://pb33f.io/libopenapi/rolodex/)

**Comment by LasneF** [comment]
[refJsonFile.json](https://github.com/pb33f/libopenapi/files/13786825/refJsonFile.json)
[specWithRef.json](https://github.com/pb33f/libopenapi/files/13786826/specWithRef.json)

here beeing the 2 files , in the SpecWithRef i put a link to refJsonFile.json 

I hope it make sens ?

**Comment by LasneF** [comment]
issue confirmed it occurs only on windows machine , the unit test arenot passing on windowsd looks , all failure are related to the $ref topic , like  TestRolodexLocalFileSystem_ProvideNonRolodexFS 

it fails with some differents case for instance 
{"time":"2024-01-10T17:21:33.1255515+01:00","level":"ERROR","msg":"unable to fetch remote document","file":"/\digitalocean\openapi\82e1d558e15a59edc1d47d2c5544e7138f5b3cbf\specification\resources\images\imageActions_list.yml","status":400,"resp":"400: Invalid request"}


should be near : index\extract_refs.go

**Comment by daveshanley** [comment]
I am going to circle back on this next week and solve this issue.

**Comment by LasneF** [comment]
issue is located in rolodex.go line 440

u, _ := url.Parse(location) 
if u != nil && u.Scheme != "" {
		isUrl = true
}

on windows , the in location we can have "C:\toto" that is so detected as a URL (with scheme  = D and opaque = \toto , Path="") 

notice that changing u.Scheme by u.Path to detect if it s really a url or no does improve a bit (but still 15 tests are failing )

**Comment by LasneF** [comment]
there is also another error that prevents test beeing successfull looks around encoding  %5C vs / or \ 
with the fix propose 

it is failing the test TestRolodexRemoteFileSystem 

got this error in the shell 
{"time":"2024-01-12T10:24:20.9500376+01:00","level":"DEBUG","msg":"loading remote file","file":"https://raw.githubusercontent.com/%5Cpb33f%5Clibopenapi%5Cmain%5Ctest_specs%5Csecond.yaml","remoteURL":"https://raw.githubusercontent.com/%5Cpb33f%5Clibopenapi%5Cmain%5Ctest_specs%5Csecond.yaml"}

**Comment by LasneF** [comment]
should be tackkled with this PR : https://github.com/pb33f/libopenapi/pull/235

**Comment by daveshanley** [comment]
Fixed in `v0.15.0` https://github.com/pb33f/libopenapi/pull/235
