### ISSUE TITLE
Consider Operation Tag Changes as Breaking Changes

### ISSUE THREAD

**Issue by tomatbay** [pb33f/libopenapi#227]
In reference to your response [here](https://github.com/pb33f/openapi-changes/issues/38#issuecomment-1603273403), I propose treating [changes](https://github.com/pb33f/libopenapi/blob/08571b76935f137b664a546f7c69610284f4565b/what-changed/model/operation.go#L128C2-L128C2) to operation tags as breaking changes. This is crucial, as alterations to these tags can potentially disrupt code generation and impact the functionality of the SDK.

**Comment by daveshanley** [comment]
Cool, I agree. Tags are critical for codegen and changing them breaks signatures. 

Please feel free to submit a PR!

**Comment by tomatbay** [comment]
Hey @daveshanley 
I've opened [PR](https://github.com/pb33f/libopenapi/pull/228) for this :)

**Comment by daveshanley** [comment]
Available in `v0.14.5`
