### ISSUE TITLE
$ref not correctly resolved  [regression]

### ISSUE THREAD

**Issue by LasneF** [pb33f/libopenapi#248]
given this file structure 

ie openapi.yaml  , then a directory called paths 
with given content for each path 

![image](https://github.com/pb33f/libopenapi/assets/12461661/f9560031-cc6e-4368-9f26-8de1fdd48b73)

it fails with this kind of errors

(notice the duplication of paths\paths  ) 

running on windows 

 INFO  Linting file '.\openapi.yaml' against 44 rules: https://quobix.com/vacuum/rulesets/recommended

ERROR unable to open the rolodex file, check specification references and base path
    ├ file: D:\code\repos\developer-portal\documentations\order-execution-management\paths\paths\releases.yaml
    └ error: open D:\code\repos\developer-portal\documentations\order-execution-management\paths\paths\releases.yaml: The system cannot find the path specified.     
ERROR unable to locate reference anywhere in the rolodex reference: paths/releases.yaml
ERROR unable to open the rolodex file, check specification references and base path
    ├ file: D:\code\repos\developer-portal\documentations\order-execution-management\paths\paths\release.yaml
    └ error: open D:\code\repos\developer-portal\documentations\order-execution-management\paths\paths\release.yaml: The system cannot find the path specified.      
ERROR unable to locate reference anywhere in the rolodex reference: ./paths/release.yaml
ERROR unable to open the rolodex file, check specification references and base path
    ├ file: D:\code\repos\developer-portal\documentations\order-execution-management\paths\paths\execution-reports.yaml
    └ error: open D:\code\repos\developer-portal\documentations\order-execution-management\paths\paths\execution-reports.yaml: The system cannot find the path specified.
ERROR unable to locate reference anywhere in the rolodex reference: paths/execution-reports.yaml
ERROR unable to open the rolodex file, check specification references and base path
    ├ error: open D:\code\repos\developer-portal\documentations\order-execution-management\paths\paths\execution-report.yaml: The system cannot find the path specified.
    └ file: D:\code\repos\developer-portal\documentations\order-execution-management\paths\paths\execution-report.yaml
ERROR unable to locate reference anywhere in the rolodex reference: paths/execution-report.yaml
ERROR unable to open the rolodex file, check specification references and base path
    ├ file: D:\code\repos\developer-portal\documentations\order-execution-management\paths\paths\releases.yaml
    └ error: open D:\code\repos\developer-portal\documentations\order-execution-management\paths\paths\releases.yaml: The system cannot find the path specified.     
ERROR unable to locate reference anywhere in the rolodex reference: paths/releases.yaml
ERROR unable to open the rolodex file, check specification references and base path
    ├ file: D:\code\repos\developer-portal\documentations\order-execution-management\paths\paths\release.yaml
    └ error: open D:\code\repos\developer-portal\documentations\order-execution-management\paths\paths\release.yaml: The system cannot find the path specified.      
ERROR unable to locate reference anywhere in the rolodex reference: ./paths/release.yaml
ERROR unable to open the rolodex file, check specification references and base path
    ├ file: D:\code\repos\developer-portal\documentations\order-execution-management\paths\paths\execution-reports.yaml
    └ error: open D:\code\repos\developer-portal\documentations\order-execution-management\paths\paths\execution-reports.yaml: The system cannot find the path specified.
ERROR unable to locate reference anywhere in the rolodex reference: paths/execution-reports.yaml
ERROR unable to open the rolodex file, check specification references and base path
    ├ file: D:\code\repos\developer-portal\documentations\order-execution-management\paths\paths\execution-report.yaml
    └ error: open D:\code\repos\developer-portal\documentations\order-execution-management\paths\paths\execution-report.yaml: The system cannot find the path specified.
ERROR unable to locate reference anywhere in the rolodex reference: paths/execution-report.yaml

**Comment by daveshanley** [comment]
This isn't a regression per se, it's a failure of the language server to pick up the current working directory. I will investigate this asap, however I have a feeling that a `vacuum.conf.yaml` with a `base` property set to `.` or the working directory should resolve it - however it should be able to figure that out

**Comment by daveshanley** [comment]
Fixed in `v0.15.8`

A test has been added: 
https://github.com/pb33f/libopenapi/blob/main/index/search_rolodex_test.go#L131
