### ISSUE TITLE
How to read stand alone OpanAPI compatible models from a separate file?

### ISSUE THREAD

**Issue by bitomaxsp** [pb33f/libopenapi#254]
Hi Dave. 

We have very complicated setup, where some models are stored in a separate files which are not referred to from main OpenAPI spec file. 

The way i was dealing with this on lib version `0.12.1` is the following:

```go
func (oai *oasInterpreter) readStandaloneModels(model *libopenapi.DocumentModel[v3high.Document], config *datamodel.DocumentConfiguration, filename string) error {
	b, err := os.ReadFile(filename)

	// If some files are not exist, that is fine
	if os.IsNotExist(err) {
		return nil
	}

	if err != nil {
		return fmt.Errorf("schema: unable to read %s: %w ", filename, err)
	}

	var node yaml.Node
	err = yaml.Unmarshal(b, &node)
	if err != nil {
		return fmt.Errorf("schema: unmarshal: %w ", err)
	}

	idx := model.Index
	node = *node.Content[0]

	if node.Tag != "!!map" {
		return fmt.Errorf("schema: expected !!map as top level node in: %s: found %q", filename, node.Tag)
	}

	var kn *yaml.Node
	for i, r := range node.Content {
		// odd index is the Key: !!str
		// even index is the object(value node), in our case: !!map

		if i%2 == 0 {
			// pick key node and continue to value node
			kn = r
			continue
		}
		fmt.Println("Node:", kn.Value)

		sp, err := constructHighProxy(kn, r, idx)
		if err != nil {
			return fmt.Errorf("schema: %s[%s:%d]: %w", kn.Value, filename, kn.Line, err)
		}
		// Save result to the model
		oai.model.Model.Components.Schemas.Set(kn.Value, sp)
	}

	return nil
}

func constructHighProxy(k, v *yaml.Node, idx *index.SpecIndex) (*base.SchemaProxy, error) {
	// Following algorithm is a standard way to create high level object when parsing schemas
	// Create empty low proxy
	lowSp := &lowbase.SchemaProxy{}

	// Build low proxy object
	err := lowSp.Build(context.Background(), k, v, idx)
	if err != nil {
		return nil, fmt.Errorf("unable to build low proxy: %w", err)
	}

	// Request schema to trigger object construction internally
	ls := lowSp.Schema()  // <- THIS IS FAILING ON 0.15.10
	if ls == nil {
		err := lowSp.GetBuildError()
		return nil, fmt.Errorf("unable to build model object: %w", err)
	}
	//  Create reference that is used to create high level proxy object
	lowRef := low.NodeReference[*lowbase.SchemaProxy]{}
	lowRef.Value = lowSp
	lowRef.KeyNode = k
	lowRef.ValueNode = v
	sp := base.NewSchemaProxy(&lowRef)
	// Build internal schema by calling it.
	if sp.Schema() == nil {
		return nil, fmt.Errorf("high build: %w", sp.GetBuildError())
	}
	return sp, nil
}
```

But when i updated to `0.15.10`, this code no longer works. 
I am fully aware this isn't standard use case maybe, but we use that approach for number of reasons.

So i am wondering is there a better approach we can use to load OpenAPI models from files not referred from the main spec? 

Thanks a lot

**Comment by daveshanley** [comment]
This should still work, I think this is a bug. There is a patch available which solves some errors I discovered during stress testing. https://github.com/pb33f/libopenapi/pull/255

**Comment by bitomaxsp** [comment]
Checked out #255. Same error still present.
I can maybe create minimal repo sample and attach it.

**Comment by bitomaxsp** [comment]
[lib1.zip](https://github.com/pb33f/libopenapi/files/14341974/lib1.zip)

If you put that to libopenapi repo root
unzip
run the test: `go test ./lib1/...`
it should show:
```sh
read_multi_test.go:35: schema: Byte[testdata/multifile/shared/scalars.yaml:15]: unable to build model object: build schema failed: reference cannot be found: '#/Uint8', line 16, col 9
```

**Comment by daveshanley** [comment]
Thanks, I will throw it into my test rig and tell you what I find.

**Comment by daveshanley** [comment]
OK, so this is not a bug (I love it when that is the case). 

There have been a number of changes to allow the internals of the index, the rolodex and the resolver to work more effectively with large numbers of super complex, deeply nested compositions.

The only change you need to make to the code, is to pass the correct context to your `SchemaProxy`. This is used to lookup the reference from a known position in time and space. These contexts are already set for you when using the constructed model `SchemaProxy` instances, however, when you're building them manually, you need to supply it. 

Here is how to modify your code, to get it to operate correctly"


### Add a filename arg to your `constructHighProxy` method
```go
func constructHighProxy(k, v *yaml.Node, idx *index.SpecIndex, filename string) (*base.SchemaProxy, error) {
```

And pass it in via `readStandaloneModels`

```go
 _, err := constructHighProxy(kn, r, idx, filename)
```

### Modify `constructHighProxy` to use the correct context

Create the correct context, using the absolute filepath of the file you're extracting from.

```go

func constructHighProxy(k, v *yaml.Node, idx *index.SpecIndex, filename string) (*base.SchemaProxy, error) {
    // Following algorithm is a standard way to create high level object when parsing schemas
    // Create empty low proxy
    lowSp := &lowbase.SchemaProxy{}

    // get the absolute path to your file
    abs, _ := filepath.Abs(filename)
    
    // construct a new proxy with the `index.CurrentPathKey` context key using the absolute filepath.
    ctx := context.WithValue(context.Background(), index.CurrentPathKey, abs)

    // Build low proxy object
    err := lowSp.Build(ctx, k, v, idx)
    ...
```

And you're compliant once again.

**Comment by bitomaxsp** [comment]
Thanks a lot. That is working well!
