### ISSUE TITLE
Parameter explode handling doesn't handle it being an optional field

### ISSUE THREAD

**Issue by TristanSpeakEasy** [pb33f/libopenapi#26]
At the moment it seems the `v3.Parameter`'s `explode` field is just a `boolean`. Meaning if its not set in the OpenAPI document it will default to the boolean's zero value of `false`. But in the case of query parameters for example, the default value should be `true`, and because the type is `boolean` (as opposed to `*boolean`) I can't tell if it is unset in the document and I should default handling of explode to `true`.

**Comment by daveshanley** [comment]
Good call, will address this in a patch.

**Comment by TristanSpeakEasy** [comment]
Just adding to this the v3.Encoding `explode` field should be handle the same (as a pointer) as it can default to true as well if style == form and its not provided

**Comment by daveshanley** [comment]
Fixed in `v0.3.1`
