### ISSUE TITLE
Render() function panics due to ignored error

### ISSUE THREAD

**Issue by SAPRD2** [pb33f/libopenapi#264]
libopenapi version: 0.15.14

The [RenderAndReload()](https://github.com/pb33f/libopenapi/blob/main/document.go#L200) function panics with the given spec due to the error being ignored at [YAMLNodeToJSON](https://github.com/pb33f/libopenapi/blob/main/json/json.go#L14) function.

The complete flow of function is: [RenderAndReload](https://github.com/pb33f/libopenapi/blob/main/document.go#L200) -> [Render](https://github.com/pb33f/libopenapi/blob/main/document.go#L221) -> [RenderJSON](https://github.com/pb33f/libopenapi/blob/main/datamodel/high/v3/document.go#L174) -> [YAMLNodeToJSON](https://github.com/pb33f/libopenapi/blob/main/json/json.go#L14) -> [handleYAMLNode](https://github.com/pb33f/libopenapi/blob/main/json/json.go#L23).

The error coming from handleYAMLNode is ``yaml: cannot decode !!float `-999.99` as a !!int``. Due to the same, the variable [newbytes](https://github.com/pb33f/libopenapi/blob/main/document.go#L202) is empty which leads to an error further in the code.

Below is a simple go program which demonstrates the same
```golang
package main

import (
	"fmt"
	"github.com/pb33f/libopenapi"
)

const openAPISpec = `{"openapi":"3.0.0","info":{"title":"dummy","version":"1.0.0"},"paths":{"/dummy":{"post":{"requestBody":{"content":{"application/json":{"schema":{"type":"object","properties":{"value":{"type":"number","format":"decimal","multipleOf":0.01,"minimum":-999.99}}}}}},"responses":{"200":{"description":"OK"}}}}}}`

func main() {

	document, _ := libopenapi.NewDocument([]byte(openAPISpec))

	_, _ = document.BuildV3Model()

	_, _, _, _ = document.RenderAndReload() // code panics here
}

```

Spec: 
```json
{
  "openapi": "3.0.0",
  "info": {
    "title": "dummy",
    "version": "1.0.0"
  },
  "paths": {
    "/dummy": {
      "post": {
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "value": {
                    "type": "number",
                    "format": "decimal",
                    "multipleOf": 1.0e-2,
                    "minimum": -999.99
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "OK"
          }
        }
      }
    }
  }
}
```

**Comment by daveshanley** [comment]
This was resolved in `v0.16.0` The error is handled and a test was added to validate

https://github.com/pb33f/libopenapi/blob/main/document_test.go#L1335
