### ISSUE TITLE
nullable: true for response validation

### ISSUE THREAD

**Issue by SimonAM** [pb33f/libopenapi#265]
Im wondering if there is support for the `nullable: true` prop?

I have a validator set up that works fine for response validation. However, when i have a model with `nullable: true`  and gets responses with matching data i get the following error:

`failed to validate schema, Reason: The response body for status code '200' is defined as an object. However, it does not meet the schema requirements of the specification, Validation Errors: [Reason: expected string, but got null, Location: /properties/myType/type]`

When i print the v3 model as json i can observe 
"myType": {"nullable": true, "type": string,....}

**Comment by daveshanley** [comment]
Unfortunately this isn't something we control. Schema validation is provided by https://github.com/santhosh-tekuri/jsonschema. We use the official OpenAPI schema and this library to validate them.
