### ISSUE TITLE
ref in schema cant parse

### ISSUE THREAD

**Issue by zhaolei0518** [pb33f/libopenapi#266]
eg:
if the responses including allOf in schema ,  cant parse ref data 

"responses": {
                    "200": {
                        "description": "列表",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/resp.Mod"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/routes.AdminLogResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }

**Comment by daveshanley** [comment]
Hi, 

`resp.Mod` is why it's failing. It's not a valid file extension. We only support and can only read JSON files or YAML files with the extension `.json` or `.yaml` or `.yml`

**Comment by zhaolei0518** [comment]
> Hi,
> 
> `resp.Mod` and is why it's failing. It's not a valid file extension. We only support and can only read JSON files or YAML files with the extension `.json` or `.yaml` or `.yml`
> 
> Change the name of the reference to not use extensions with a period and you should be good to go.

Thank you for your reply.

sorry. yesterday‘s demo may be too simple. so this is a example about the issue

`{
	"swagger": "2.0",
	"info": {
		"contact": {}
	},
	"paths": {

		"/open/app/add": {
			"post": {
				"description": "新增应用",
				"produces": [
					"application/json"
				],
				"tags": [
					"OpenApiForOut"
				],
				"summary": "应用管理-添加应用信息",
				"parameters": [{
					"description": "请求参数",
					"name": "请求参数",
					"in": "body",
					"required": true,
					"schema": {
						"$ref": "#/definitions/routes_CreateAppRequest"
					}
				}],
				"responses": {
					"200": {
						"description": "列表",
						"schema": {
							"allOf": [{
									"$ref": "#/definitions/resp_Mod"
								},
								{
									"type": "object",
									"properties": {
										"data": {
											"$ref": "#/definitions/routes_CreateAppResponse"
										}
									}
								}
							]
						}
					}
				}
			}
		},
	},
	"definitions": {
		"resp_Mod": {
			"type": "object",
			"properties": {
				"code": {
					"type": "integer"
				},
				"data": {},
				"msg": {
					"type": "string"
				}
			}
		},
		"routes_CreateAppRequest": {
			"type": "object",
			"required": [
				"name"
			],
			"properties": {
				"app_type": {
					"description": "web应用1 桌面应用2",
					"type": "integer"
				}
			}
		},
		"routes_CreateAppResponse": {
			"type": "object",
			"properties": {
				"app_type": {
					"type": "integer"
				}
			}
		}
	}
}`

What you mean is that the definition of ref includes delimiters. but this demo in swagger ui is ok ,and when i use the BuildV2Model to parse , the ref is still empty.

**Comment by daveshanley** [comment]
The swagger model is lacking a lot of functionality unfortunately, the library only really focuses on openapi (v3+ model).

If I have time, I will look into this, but unfortunately, that won't be for the forseeable future. Swagger is a commercial product by smartbear, OpenAPI is an open standard and really where this project is focused. 

https://pb33f.io/libopenapi/swagger/#some-friendly-advice
https://pb33f.io/libopenapi/modifying/
