### ISSUE TITLE
Suggestion: ReadOnly/WriteOnly are *bool but could be simplified to bool

### ISSUE THREAD

**Issue by TristanSpeakEasy** [pb33f/libopenapi#30]
`ReadOnly`/`WriteOnly` are `*bool` but could be simplified to `bool` as they default to false always. It is always a bit awkward in Golang to work with pointers and if possible its great to avoid them especially when the absence of a value in the yaml/json doc defaults to false

**Comment by daveshanley** [comment]
Fixed in `v0.3.1`
