### ISSUE TITLE
Example not compiling due to error: cannot range over docModel.Model.Paths.PathItems

### ISSUE THREAD

**Issue by ajb-neodynamics-io** [pb33f/libopenapi#304]
I'm following the example illustrated here:
https://quobix.com/articles/parsing-openapi-using-go/

But I'm running into an issue where I'm getting a compile error:
`internal/config/config.go:131:34: cannot range over docModel.Model.Paths.PathItems (variable of type *"github.com/pb33f/libopenapi/orderedmap".Map[string, *"github.com/pb33f/libopenapi/datamodel/high/v3".PathItem])`

The code I'm attempting to run is exactly the same as the code in the tutorial. I literally cut and paste it:
<img width="831" alt="image" src="https://github.com/pb33f/libopenapi/assets/115384296/9e4fa094-3c01-4ebd-9248-e7793fd6133b">

Any idea why I continue to get the following error:
<img width="1334" alt="image" src="https://github.com/pb33f/libopenapi/assets/115384296/ee59ac91-bcbc-4d0b-86b5-bb9d755d45e9">

MacOS version Sonoma 14.5
Go version 1.22
libopenapi version 0.16.8

**Comment by ajb-neodynamics-io** [comment]
I though it may be because the `petstorev3.json` file that the tutorial prompts you to download is actually written in `yaml`, but changing the extension to `.yaml` did not work, same error.

**Comment by ajb-neodynamics-io** [comment]
Trying another example from the "Installing" section of the guide works as expected:
<img width="810" alt="image" src="https://github.com/pb33f/libopenapi/assets/115384296/d87b800e-5684-46f2-a7ad-a45c043d9dfc">

And I get the expected result:
<img width="426" alt="image" src="https://github.com/pb33f/libopenapi/assets/115384296/78e4d204-d97a-4e08-b6cc-ca40518c1267">

**Comment by daveshanley** [comment]
Hi There, This is the same issue as #263 

I need to update my blog is the correct answer - the API changed a while back and it means we now use ordered maps, instead of a regular map. This allows us to keep ordering in place when re-rendering the spec back out. 

I will now go and update my blog however.

**Comment by daveshanley** [comment]
OK. I updated the blog! The example code is using the new API and I added some notes.

Thank you for the nudge!
