### ISSUE TITLE
Server Variables Object is missing extensions

### ISSUE THREAD

**Issue by yagnasrinath** [pb33f/libopenapi#323]
Server Variables object can have extensions and Value Object is missing extensions
https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.3.md#server-variable-object

**Comment by geffersonFerraz** [comment]
https://github.com/pb33f/libopenapi/pull/326

**Comment by daveshanley** [comment]
Available in `v0.18.1`
