### ISSUE TITLE
Support extensions for `info.contact` object in OpenAPI 3.1.0

### ISSUE THREAD

**Issue by dani2819** [pb33f/libopenapi#330]
### Current Behavior

When parsing an OpenAPI 3.1.0 document with extensions in the `info.contact` object, the library removes the extensions under `info.contact`. This results in loss of custom metadata that is intended to be retained for various use cases.

### Expected Behavior

According to the [OpenAPI 3.1.0 specification](https://swagger.io/specification/), it is valid to use extensions (properties starting with `x-`) within the `info.contact` object. The library should correctly parse and retain these extensions.

Example of a valid OpenAPI 3.1 document:

```yaml
openapi: 3.1.0
info:
  title: Sample API
  version: 1.0.0
  contact:
    name: API Support
    x-custom-extension: "Custom Extension Value"
paths: {}
```

### Steps to Reproduce

1. Create an OpenAPI 3.1.0 document that includes extensions within the `info.contact` object.
2. Use the library to parse the OpenAPI document.
3. Observe that the extensions are missing in the parsed output.

### Example Code
```
package main

import (
	"github.com/pb33f/libopenapi"
	"os"
)

func main() {
	oasFile, _ := os.ReadFile("sample.yaml")
	document, _ := libopenapi.NewDocument(oasFile)
	document.BuildV3Model()
	b, _ := document.Render()
	_ = os.WriteFile("output.yaml", b, 0644)
}
```

The output.yaml does not contain `x-` properties under `info.contact`

### Environment

- Library Version: [v0.16.10]
- OpenAPI Version: [3.1.0]
- Go Version: [1.23.0]
- Operating System: [macOS Sanoma 14.5]

**Comment by daveshanley** [comment]
This was fixed here: https://github.com/pb33f/libopenapi/commit/0200809765f7018b6fe4ee14cf6d148e77761f6e

This issue cannot be re-created anymore with `libopenapi` `v0.18.1`+
