### ISSUE TITLE
UnpackExtensions has trouble matching struct fields to extension fields when casing differs

### ISSUE THREAD

**Issue by pzhou-splunk** [pb33f/libopenapi#34]
The new `UnpackExtensions` function introduced in `v0.3.2` seems to have trouble when the casing between the field of a Golang struct and its intended field in the extension of the API spec differs

For example, `foobar` in

```
x-custom-extension:
   foobar: baz
```

be matched and written to the field `Foobar` in 
```
type myStruct struct {
    Foobar string
}
```

but `FooBar`, `fooBar`, or `foo_bar` will not match the struct field `FooBar` 
```
x-custom-extension:
   FooBar: baz
   fooBar: baz
   foo_bar: baz
```

```
type myStruct struct {
    FooBar string
}
```

**Comment by daveshanley** [comment]
Nice find! I am concerned the problem lies here: https://pkg.go.dev/gopkg.in/yaml.v3#Node.Decode as that's whats doing all the heavy lifting here. I will look into this ASAP.

**Comment by daveshanley** [comment]
After investigating a little, I remembered something important. This isn't actually a bug, and it's part of how marshaling and unmarshalling work in go. You need to customize the encoding using hints.

When building structs that use mismatched properties that don't match the case of the JSON or YAML you want to marshal into, you need to provide meta-data that explains how to unpack those fields against a JSON or YAML key. 

For example, here is some YAML

```
numCandles: 1
addFrosting: true
birthdayMessage: happy birthday
```
if your struct uses property names that cannot be explicitly matched, you need to provide metadata in the struct to help the 
marshaling code knows which properties match which fields. 

So for example the following struct would never have anything populated:

```
type Cake struct {
  Num_Candles int                   // wrong
  addFrosting bool                  // wrong
  birthday_Message: string     // wrong
}
```

So how do you add meta-data?

After the property, you need to add a 'hint' to tell the unmarshalling code how to map those properties correctly. So your struct will end up looking like this:

```
type Cake struct {
  Num_Candles int               `json:"numCandles", yaml:"numCandles"`
  addFrosting bool               `json:"addFrosting", yaml:"addFrosting"`  // lowercase is auto-ignored by default
  birthday_Message: string  `json:"birthdayMessage", yaml:"birthdayMessage"`
}
```

Everything will work as expected. Properties can be correctly mapped to JSON or YAML data.

To learn a little more about this, you can read here: 
https://drstearns.github.io/tutorials/gojson/#seccustomizingtheencoding

**Comment by pzhou-splunk** [comment]
Thank you for the explanation! Closing the issue
