### ISSUE TITLE
Creating a validator for HTTP request/responses

### ISSUE THREAD

**Issue by jamietanna** [pb33f/libopenapi#36]
While considering moving to this, from kin-openapi, one big usecase that'd be handy to have support for is being able [to perform request/response validation](https://github.com/getkin/kin-openapi/#validating-http-requestsresponses) according to the spec.

Is this something you'd see being officially as part of this package, or a separate package that builds on top of this one? I'd be interested in helping get this over the line, but thought I'd check first where this would best fit.

**Comment by daveshanley** [comment]
Hi Jamie, 

Yes, this is very much on the roadmap. I see this being an essential feature of `libopenapi` soon. It would be a new module called `validation`, and we would build code in there that uses the other modules like the `datamodel` and documents to provide the same excellent functionality that `kin-openapi` provides.

The feature does not exist yet. It's on my radar, however. January/February 2023 timeframe is when I will be able to start work on it. Unless you want to take a look at it?

Thanks.

**Comment by zekth** [comment]
Is there any update on this or branches to look at / contribute to? I'd be happy to give it a shot :)

**Comment by daveshanley** [comment]
I'm going to work on this feature next.

**Comment by daveshanley** [comment]
If you want to follow along as this feature is built out, work is happening here daily: https://github.com/pb33f/libopenapi-validator

The validator will be another package that depends on libopenapi, it will validate http requests and responses as well as documents.

**Comment by daveshanley** [comment]
`v0.0.1` of `libopenapi-validator` is available at https://github.com/pb33f/libopenapi-validator

**Comment by daveshanley** [comment]
Documentation is online at: https://pb33f.io/libopenapi/validation/

There will be bugs, but let's move the conversation over to: https://github.com/pb33f/libopenapi-validator
