### ISSUE TITLE
Schema `not` should be a single proxy instead of array

### ISSUE THREAD

**Issue by danielgtaylor** [pb33f/libopenapi#38]
Similar to #28, it looks like `not` should be a single item instead of an array.

- https://json-schema.org/understanding-json-schema/reference/combining.html#not
- https://json-schema.org/draft/2020-12/json-schema-core.html#section-10.2.1.4
- https://github.com/pb33f/libopenapi/blob/main/datamodel/high/base/schema.go#L59

It also looks like maybe conditional subschemas via [`if`, `then`, `else`](https://json-schema.org/draft/2020-12/json-schema-core.html#section-10.2.2) are missing as well, but :scream: :skull:...

**Comment by daveshanley** [comment]
Please check PR #40
