### ISSUE TITLE
Feature Request: IsReference() and GetReference() methods for low level models

### ISSUE THREAD

**Issue by TristanSpeakEasy** [pb33f/libopenapi#41]
As discussed in this issue https://github.com/pb33f/libopenapi/issues/25

It would be great to be able to easily determine if high level models (via their GoLow() low level model) where resolved from references.

Some of the types we need to determine are references are mentioned in this swagger documentation https://swagger.io/docs/specification/components/

**Comment by daveshanley** [comment]
Will work on this ASAP.

**Comment by daveshanley** [comment]
@TristanSpeakEasy This is available in `v0.7.0`
