### ISSUE TITLE
Runtime error when input does not meet the OpenAPI specification

### ISSUE THREAD

**Issue by sergeyklay** [pb33f/libopenapi#44]
Hi,

I create my small validator based on libopenapi.

Unfortunately, any attempt to access an `OperationId` that does not appear to exist in the source document will result in the following runtime error:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x20 pc=0x102ec4748]
```

Here is a simplified function to show how I played with it:

```go
func validateDoc(model *libopenapi.DocumentModel[v3high.Document]) {
	for _, item := range model.Model.Paths.PathItems {

		// Here is my playground

	}
}
```

Ways I've tried:

- item.Options.OperationId
- item.Options.GoLow().OperationId
- ...

I tried to get up with reflection and other black magic, but unfortunately there was no success.

Could you advise me the most ideomatic way to check the presence of fields? Below I provide a file to reproduce the error.

```yaml
openapi: 3.0.3
info:
  version: 1.0.0
  title: Example
servers:
  - url: 'http://127.0.0.1:8080'
paths:
  /v1/foo:
    get:
      summary: Some summary
      responses:
        '204':
          description: No content
```

---

My environment:

```
% go version
go version go1.19.4 darwin/arm64
```

```
% uname -a
Darwin Mercury.local 22.1.0 Darwin Kernel Version 22.1.0: Sun Oct  9 20:14:30 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T8103 arm64
```

The project's `go.mod` file I'm playing with looks like this (the significant part):

```
// omitted for brevity

require (
	github.com/pb33f/libopenapi v0.4.0
	github.com/spf13/afero v1.9.3
	github.com/spf13/cobra v1.6.1
)

require (
	github.com/dprotaso/go-yit v0.0.0-20220510233725-9ba8df137936 // indirect
	github.com/inconshreveable/mousetrap v1.0.1 // indirect
	github.com/spf13/pflag v1.0.5 // indirect
	github.com/stretchr/testify v1.8.1 // indirect
	github.com/vmware-labs/yaml-jsonpath v0.3.2 // indirect
	golang.org/x/text v0.3.7 // indirect
	gopkg.in/yaml.v3 v3.0.1 // indirect
)
```

**Comment by sergeyklay** [comment]
Probably the problem is slightly different and I mistakenly used this incorrectly. However, it is noteworthy that it can lead to the panic. Bellow are other ways to face a similar issue.

Prepare the code to test:
```go
func testMe(model *libopenapi.DocumentModel[v3high.Document]) {
	for url, path := range model.Model.Paths.PathItems {
		for method, op := range path.GetOperations() {
			fmt.Printf("path: %s, operation: %s (%s)\n", url, method, op.OperationId)
		}
	}
}
```

And some test data:


**panic: runtime error: invalid memory address or nil pointer dereference**
```yaml
openapi: 3.0.3
```

**panic: runtime error: invalid memory address or nil pointer dereference**
```diff
  openapi: 3.0.3
+ paths:
```

**All is OK. Test passed**
```diff
  openapi: 3.0.3
+ components:
  paths:
```

**All is OK. Test passed**
```diff
  openapi: 3.0.3
  components:
  paths:
+   /v1/users:
+     get:
+       responses:
+         '204':
+           description: No content
```

**panic: runtime error: invalid memory address or nil pointer dereference**
```diff
  openapi: 3.0.3
- components:
  paths:
    /v1/users:
      get:
        responses:
          '204':
            description: No content
```

**panic: runtime error: invalid memory address or nil pointer dereference**
```diff
  openapi: 3.0.3
  paths:
    /v1/users:
      get:
+       operationId: users.list
        responses:
          '204':
            description: No content
```


**All is OK. Test passed**
```diff
  openapi: 3.0.3
+ components:
  paths:
    /v1/users:
      get:
        operationId: users.list
        responses:
          '204':
            description: No content
```

Well, apparently I lack some way to check the validity of a spec before parsing it, since the document comes from the outside (user input) and I can't guarantee that it meets the OpenAPI specification.

**Comment by daveshanley** [comment]
Hi Sergey, 

I ran your first snippet of code:

```go
for url, path := range model.Model.Paths.PathItems {
    for method, op := range path.GetOperations() {
        fmt.Printf("path: %s, operation: %s (%s)\n", url, method, op.OperationId)
     }
}
```

I got the following output:

`path: /v1/foo, operation: get ()`

This is the **correct behavior.**

As I read your examples, I think you may be overlooking a core principal of the model. 

> You cannot navigate through that which is not there

For example, if you take this test snippet:

```diff
  openapi: 3.0.3
+ paths:
```

And you write code that explicitly calls on something that does not exist:

`for url, path := range model.Model.Paths.PathItems {`

This will always throw a panic if you try to navigate to an object that isn't there in this case, there are no `PathItems` so trying to use that property of `Paths` will fail. `PathItems` is `nil`, there are _none_ in the spec.

If you look at the model for `Paths` (https://github.com/pb33f/libopenapi/blob/a9eb20a375074390ecc22409726fc5557d9227fa/datamodel/high/v2/paths.go#L13)

You can see that the `PathItems` is a map

```go
type Paths struct {
    PathItems  map[string]*PathItem  
    Extensions map[string]any
    low        *low.Paths
}
```

This means if there are no `PathItems` the map is `nil`, and everything else will be `nil`.

So you won't be able to just blindly call every properly of every object, if you check the API, they are mostly ALL pointers, which will always be `nil` if they are not set in the specification. For every property, unless it's a primitive, you will need to check it's not `nil`, so to fix your code above, you would need to do this:

```go
 model, errs := doc.BuildV3Model()
    if len(errs) > 0 {
        panic(errs)
    }

    if model.Model.Paths != nil {
        for url, path := range model.Model.Paths.PathItems {
            for method, op := range path.GetOperations() {
                fmt.Printf("path: %s, operation: %s (%s)\n", url, method, op.OperationId)
            }
        }
    } else {
        fmt.Println("No paths!")
    }
```

There isn't anything for me to fix here as this is all desired behavior. So to discuss your other desire: Validation. 

It will be a very, very big job to try and use the `libopenapi` model to validate an OpenAPI specification. The spec is huge, and going through every variation and combination would take some time.

If you want to know how much work it would be, [take a look at the `what-changed` module](https://github.com/pb33f/libopenapi/tree/main/what-changed/model). That code performs a deep, 1-1 check of everything
between two specs - there is a lot of code.

What I would recommend for validation is that you validate the spec BEFORE reading it into a model using `libopenapi`.

The easiest and most reliable way to do this is to use JSON Schema. 

1. Read in the OpenAPI Schema for which ever version you're using [here is the 3.0 schema](https://github.com/OAI/OpenAPI-Specification/blob/main/schemas/v3.0/schema.json)
2. Use https://github.com/santhosh-tekuri/jsonschema to validate the OpenAPI spec against the schema. 
3. If it's valid - you're ready to now use `libopenapi`
4. Don't forget to check for `nil`

I hope this helps. Thanks for using my tool!

**Comment by sergeyklay** [comment]
@daveshanley Thank you for your response! Many things do become clearer thanks to your answer. However, I just wanted to point out that currently libopenapi still needs to pre-check OpenAPI documents using third-party tools, as well as libopenapi design relies on the fact that user input meeting the specification.

Btw, what about this document and the test code [I mentioned above](https://github.com/pb33f/libopenapi/issues/44#issuecomment-1347945690)? This document leads to segfault
```yaml
openapi: 3.0.3


paths:
  /v1/users:
    get:
      summary: Some summary
      operationId: users.list
      responses:
        '204':
          description: No content
```

**Comment by daveshanley** [comment]
Hi Sergey, 

Regarding third-party code being required for validation - yes, you're right. Eventually, this will be made available as a utility along side request/response validation, see #36.

I ran this code: 

```go
    var operations []string
    duplicated := false
    for url, path := range model.Model.Paths.PathItems {
        for method, op := range path.GetOperations() {
            if len(op.OperationId) > 0 {
                if slices.Contains(operations, op.OperationId) {
                    fmt.Printf("Semantic error at paths.%s.%s.operationId\n", url, method)
                    fmt.Printf("Operations must have unique operationIds.\n\n")

                    duplicated = true
                    continue
                }
                operations = append(operations, op.OperationId)
            }
        }
    }
    fmt.Println(duplicated)
```

Against this spec:

```yaml
openapi: 3.0.3
info:
  version: 1.0.0
  title: Example
servers:
  - url: 'http://127.0.0.1:8080'
paths:
  /v1/foo:
    get:
      summary: Some summary
      responses:
        '204':
          description: No content
```

No error, no panic, no segfault. I am unable to re-produce this error.

**Comment by sergeyklay** [comment]
Well, it must be some kind of build issue. At least I did not change the code in this module, but added new dependencies to the project and the problem went away.

I'm going to close this issue because I can't reproduce it anymore (although I didn't change the code);

Thanks for your patience and answers.
