### ISSUE TITLE
Bug: Some references are failing to build because they can't be found but are valid in the document

### ISSUE THREAD

**Issue by TristanSpeakEasy** [pb33f/libopenapi#45]
For example for this OpenAPI document: https://github.com/speakeasy-api/openapi-directory/blob/main/APIs/nexmo.com/conversation/2.0.1/openapi.yaml

At `line 982` it has a ref `#/components/schemas/channel/properties/from/oneOf/0` that exists in the doc at `line 883`

The error I get is `reference cannot be found: #/components/schemas/channel/properties/from/oneOf/0, line 982, col 21`

**Comment by daveshanley** [comment]
Oh, interesting. It seems integers as keys are being ignored. I'll investigate

**Comment by daveshanley** [comment]
This is more tricky than at first glance. The index has them recorded, but this kind of embedded lookup is a use case I've not encountered before. I'll need to look a little deeper at this as it's a valid (but somewhat bizzare) use case.

**Comment by TristanSpeakEasy** [comment]
Let me know if you need more examples of this, I'm pretty sure I saw this a few more times in our directory https://github.com/speakeasy-api/openapi-directory/tree/main/APIs

**Comment by TristanSpeakEasy** [comment]
Okay I found some more examples that are doing strange things with references that are still valid:

https://github.com/speakeasy-api/openapi-directory/blob/main/APIs/digitalocean.com/2.0/openapi.yaml

uses references like `#/paths/~1v2~1apps~1%7Bapp_id%7D~1deployments/get/responses/200/content/application~1json/schema/properties/deployments/items` on `line 1757`

**Comment by TristanSpeakEasy** [comment]
https://github.com/speakeasy-api/openapi-directory/blob/main/APIs/github.com/ghes-2.18/1.1.4/openapi.yaml

is using `#/components/schemas/gpg-key/properties/subkeys/example/0/expires_at` on `line 32802` 

this one is quite strange referencing values from an example in other places

**Comment by TristanSpeakEasy** [comment]
These strange refs are not very common (ie not many of the documents reference in this way) but all the github openapi docs do use a similar reference pattern to that shown above which means we can't parse any of those specs. Not entirely sure if the way they are using them is valid, the openapi/json schema specs aren't super clear on where refs can be used and what can be referenced. 

But as an example the OpenAPI extension for VSCode is able to resolve all these refs and doesn't lint them as invalid

**Comment by daveshanley** [comment]
They are valid refs, the technique is not invalid, it's just a bit nuts in my opinion. I've spent some time with crazy refs like `#/paths/~1v2~1apps~1%7Bapp_id%7D~1deployments/get/responses/200/content/application~1json/schema/properties/deployments/items ` (the ~1 is encoded slashes for referring to paths.)

I'm going to dig into to this a little more over the next couple of days, it's a bit of a tricky one to nail down.

**Comment by daveshanley** [comment]
Woo, man these references are nuts! looking into it.

**Comment by daveshanley** [comment]
> So it seems the original reference is fixed but then I got `schema properties build failed: cannot find reference #/components/schemas/channel/properties/from/oneOf/1/properties/number, line 25, col 990` BTW it looks like the line and column numbers here a switched (it should be line 990)

Which spec is this?

**Comment by TristanSpeakEasy** [comment]
The one originally linked

**Comment by daveshanley** [comment]
Can you try `v0.4.5`?

**Comment by TristanSpeakEasy** [comment]
Can confirm looks to be all fixed thank you!
