### ISSUE TITLE
feature request: add index for getting all "schema" objects

### ISSUE THREAD

**Issue by TristanSpeakEasy** [pb33f/libopenapi#50]
At the moment there is a GetAllSchemas method on an index but this is a little misleading as this is only returning schemas that live within components/schemas.

**Comment by daveshanley** [comment]
Does `GetMappedReferences()` Do the job? 

https://github.com/pb33f/libopenapi/blob/main/index/spec_index.go#L359

**Comment by TristanSpeakEasy** [comment]
I don't think so as I am looking for both inline schemas and schemas that were mapped from a reference, unless I misunderstand what this contains.

Basically I need to iterate over every object and validate their properties are unique

**Comment by TristanSpeakEasy** [comment]
Just to add to this I also need to just loop over every schema object in a document period. Basically I need to do a level of validation on the schemas that a lot of other tooling isn't currently because of our use case

**Comment by daveshanley** [comment]
This should be resolved in `v0.5.0.`

The original behavior of `GetAllSchemas()` has been moved to a new method called `GetAllComponentSchemas()`

There are two new methods available:

1. `GetAllInlineSchemas()`
2. `GetAllInlineSchemaObjects()`

`GetAllInlineSchemas()` will return a `Reference` to every mention of `schema` in the document, excluding references. 

`GetAllInlineSchemaObjects()` returns everything the former does, except it's filtered to only schemas of type `object` or `array.`

The replaced `GetAllSchemas()` returns a combination of `GetAllInlineSchemas()` and `GetAllComponentSchemas()` in an easy-to-iterate slice.

Let me know if it works for you.

**Comment by TristanSpeakEasy** [comment]
Thank you for this should be super helpful for what we are doing, I won't be able to try it out for a couple of days but will feedback as soon as I have given it a go

**Comment by daveshanley** [comment]
Did you manage to try this out?

**Comment by TristanSpeakEasy** [comment]
No it totally fell of the radar with other priorities in the way but I should have some time today to confirm

**Comment by TristanSpeakEasy** [comment]
Hey @daveshanley I just tried this out and it looks like it is largely working as I expected apart from the path in the index.Reference for example for an inline schema within a response schema I got `$.paths./test.get.responses.200.content.application/json` for the path but would have expected `$.paths./test.get.responses.200.content.application/json.schema`

**Comment by TristanSpeakEasy** [comment]
Actually adding to this after further testing it doesn't seem inline schemas within parent schemas are within the index.

For example:

```yaml
openapi: 3.1.0
servers:
  - url: http://localhost:8080
paths:
  /test:
    get:
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  test:
                    type: array
                    items: true
```

The array schema above is available in the index

**Comment by daveshanley** [comment]
I have tuned this functionality up; it was not checking `properties` once a schema was found, which is a pretty big hole! so now that's been fixed. Let me know how you get on.

**Comment by TristanSpeakEasy** [comment]
@daveshanley this particular issue is sorted thank you. I will open new tickets if I find anything else
