### ISSUE TITLE
BUG: AllOf sequence order is not preserved on parsing

### ISSUE THREAD

**Issue by bitomaxsp** [pb33f/libopenapi#58]
`AllOf` is expressed as sequence in yaml. On parsing it to high schema object order is not preserved, and even more, on each parse it is random. Also `Low.AllOf` and `high.AllOf` order are different.

For composition we rely on certain field order in the array therefore its crucial to maintain the order in high and low objects same as in yaml.Node. Of course one may argue that original order can be extracted from yaml.Node which is true. But then I think purpose of the library diminishes as we can just work with yaml.Node directly all the time. 
We use Open API to generate our API to different languages and platforms where order matters and it would be nice to rely on that on lib level objects too.

**Comment by bitomaxsp** [comment]
#59 fails

**Comment by daveshanley** [comment]
Hi, I'm offline for a couple of days during the holidays (I've not had any downtime this year), so, I haven't been able to look into this yet. I'm unsure why the ordering is different, but I can understand it being an issue.

I'll be back online in a couple of days and I can investigate this a little more. A fix should be nonbreaking.

**Comment by bitomaxsp** [comment]
I have suggested a fix. Please review when you have time. 
It fixes all arrays processing, not only AllOf

**Comment by daveshanley** [comment]
I've added some comments. Generally, it looks OK, but I want to ensure we're not slowing things down for large specs, I don't think it will, but I want to make sure. So some A/B benchmark testing to verify it's not slowing things down (even though I'm pretty sure it won't)

**Comment by bitomaxsp** [comment]
Will try to comeup with some benchmarks. 
But i think you forgot to submit your comments. I do not see them

**Comment by daveshanley** [comment]
Apologies forgot to press submit, I got distracted with some code.

**Comment by TristanSpeakEasy** [comment]
Have just ran into this issue as well, as order of allOf determines how the resulting object is resolved and if the order is incorrect then things may not be overridden correctly (if two allOf schemas specify the same fields for example the first one in the list gets overriden by the second one in the list for example)

**Comment by daveshanley** [comment]
Once we're confident about the change @bitomaxsp has put in place in #59, this should be resolved.

**Comment by TristanSpeakEasy** [comment]
I have provided an alternate PR that retains the async nature of the resolving while solving the original order issue here https://github.com/pb33f/libopenapi/pull/66

**Comment by daveshanley** [comment]
Now that #66 has been merged in (thank you for your contribution @TristanSpeakEasy). We should be able to close the book on this issue.
