### ISSUE TITLE
Unable to resolve relative URL references

### ISSUE THREAD

**Issue by danielgtaylor** [pb33f/libopenapi#73]
I love the DigitalOcean OpenAPI spec ([raw](https://raw.githubusercontent.com/digitalocean/openapi/main/specification/DigitalOcean-public.v2.yaml) | [github](https://github.com/digitalocean/openapi/tree/main/specification)) for its ability to break tools: loads of relative references and even the text fields like `description` use `$ref`s to separate YAML files containing Markdown prose. It seems like libopenapi can't load it when loading from a URL due to the references:

```sh
$ restish digitalocean --help
panic: errors [path item build failed: cannot find reference: resources/1-clicks/oneClicks_install_kubernetes.yml at line 539, col 13]
```

That makes sense, because when creating a new `libopenapi.Document` you don't pass in a base URI, just the loaded bytes of the YAML. The [code to determine whether some reference should be loaded via HTTP](https://github.com/pb33f/libopenapi/blob/main/index/spec_index.go#L1684) is run much later down the chain:

```go
func DetermineReferenceResolveType(ref string) int {
	if ref != "" && ref[0] == '#' {
		return LocalResolve
	}
	if ref != "" && len(ref) >= 5 && (ref[:5] == "https" || ref[:5] == "http:") {
		return HttpResolve
	}
	if strings.Contains(ref, ".json") ||
		strings.Contains(ref, ".yaml") ||
		strings.Contains(ref, ".yml") {
		return FileResolve
	}
	return -1
}
```

From the [OpenAPI 3.1.0 spec](https://spec.openapis.org/oas/v3.1.0#relative-references-in-uris):

> Unless specified otherwise, all properties that are URIs MAY be relative references as defined by [[RFC3986](https://spec.openapis.org/oas/v3.1.0#bib-RFC3986)].
> 
> Relative references, including those in [Reference Objects](https://spec.openapis.org/oas/v3.1.0#referenceObject), [PathItem Object](https://spec.openapis.org/oas/v3.1.0#pathItemObject) $ref fields, [Link Object](https://spec.openapis.org/oas/v3.1.0#linkObject) operationRef fields and [Example Object](https://spec.openapis.org/oas/v3.1.0#exampleObject) externalValue fields, are resolved using the referring document as the Base URI according to [[RFC3986](https://spec.openapis.org/oas/v3.1.0#bib-RFC3986)].

This doesn't seem like a quick fix, so I wanted to open this issue to discuss how to approach it.

My suggestion is to have the document take a base URI which could be a file path or URL, and any reference handling code should respect that and resolve the reference against the base unless it's a fully qualified URI itself (e.g. beings with `https://...`). This is somewhat similar to how [kin-openapi approaches it](https://github.com/getkin/kin-openapi/blob/master/openapi3/loader.go#L145-L150) by taking bytes and a location (file path or URL).

To anyone who stumbles across this issue, there are two workarounds currently:
1. Update relative references to fully qualified URLs.
2. Download all files locally and load from disk.

**Comment by daveshanley** [comment]
I stumbled across this also when I was doing some testing. I thought it would be best to circle back to it once bug reports had died down a little. It's something we need to tackle for sure.

**Comment by TristanSpeakEasy** [comment]
Just adding a plus one here, it would be great to be able to provide some search path for relative references, as especially in our use case the "root" document could come from one location and we want the lib to lookup the references in another location.

It would be an added bonus if this was file system independent and could provide options for using https://pkg.go.dev/io/fs   so the docs could be resolved from memory, a database, on disk or a url

**Comment by n0rig** [comment]
If I understand correctly, SPECs with relative `$ref`s should be loaded using the initial manner the root document was loaded. For example:
* if loaded via local filesystem, all the `$ref`s should be relative to the root spec document on the local filesystem
* if loaded over network, all the the `$ref`s should be relative to the URI of the original document.

However, if the $refs are full URIs, just load those (e.g. if they all are http URIs `$ref`s).

**Comment by bitomaxsp** [comment]
Do you need any help implementing it? Asking because we kind of lacking this feature as our spec grows quite quickly now.

**Comment by daveshanley** [comment]
I am going to start working on this feature at the end of march, if no-one else picks it up before then.

**Comment by bitomaxsp** [comment]
I can try to look into it. Late of march is to late for us. Do you have any pointer or advises?

**Comment by daveshanley** [comment]
Just an FYI, the digital ocean spec is made up of 1378 individual files.

**Comment by daveshanley** [comment]
Please take a look at #83 at your convenience.

**Comment by daveshanley** [comment]
an FYI, I plan on merging #83 within 24 hours, so speak now if you have any feedback.

**Comment by TristanSpeakEasy** [comment]
My only feedback would be regarding our use case which is the ability to define a filesystem or some other override for controlling where the lookups happen as in most circumstances we are doing things all in memory so filesystem reads don't work for us

**Comment by daveshanley** [comment]
> My only feedback would be regarding our use case which is the ability to define a filesystem or some other override for controlling where the lookups happen as in most circumstances we are doing things all in memory so filesystem reads don't work for us

Yes, this is a good idea, and I will add it as a new feature to upgrade the indexer to use this abstraction. It's a good deal of surgery, but I don't want to overload this change, which is already a lot of shifting with the potential for regression if I've missed anything.

**Comment by bitomaxsp** [comment]
I'll test right away!
