### ISSUE TITLE
Ability to provide a search path for external references

### ISSUE THREAD

**Issue by TristanSpeakEasy** [pb33f/libopenapi#79]
I believe currently libopenapi is searching for external references ie things like `$ref: 'external.yaml#/components/schemas/Item'` within the current working directory.

This unfortunately limits the usability of loading external references for us as we provide the ability to specify a path to a document that could live outside the current working directory of our application and in this case we get errors like: `schema build failed: reference 'external.yaml#/components/schemas/Item' cannot be found at line 15, col 23` (btw would be useful if the error could contain more info like where it is trying to find the file).

What I propose is providing a way to specify search directories (or even just a single working directory) to a `libopenapi.Document` 

ie something like:

```go
doc, err := libopenapi.NewDocument(mainYaml)
if err != nil {
	panic(err)
}

doc.SetSearchDirectories([]string{".", "./specs"})

m, errs := doc.BuildV3Model()
if errs != nil {
	panic(errs)
}
```

**Comment by daveshanley** [comment]
Is this a duplicate of #73?

**Comment by TristanSpeakEasy** [comment]
I don't think so as I could be providing the byte array from anywhere but want to point libopenapi at a particular place on disk to resolve non uri based paths, but maybe I a misunderstanding the other use case.

And added bonus would be being able to provide a file system to do the look up in

**Comment by TristanSpeakEasy** [comment]
Actually it does look similar I will add my particular use case to that
