### ISSUE TITLE
Cannot resolve local reference errors on references that reference paths that traverse through other references

### ISSUE THREAD

**Issue by TristanSpeakEasy** [pb33f/libopenapi#84]
So we get the below errors:

```
ERROR   validation error: [line 3989] failed to build model: cannot resolve reference `#/paths/~1companies~1%7BcompanyId%7D~1data~1bills/get/responses/200/content/application~1json/schema/allOf/0/properties/results/items/properties/lineItems/items/properties/tracking/properties/isBilledTo`, it's missing: $.paths['/companies/{companyId}/data/bills'].get.responses['200'].content['application/json'].schema.allOf[0].properties.results.items.properties.lineItems.items.properties.tracking.properties.isBilledTo [3989:21]
ERROR   validation error: [line 3989] failed to build model: cannot resolve reference `#/paths/~1companies~1%7BcompanyId%7D~1data~1bills/get/responses/200/content/application~1json/schema/allOf/0/properties/results/items/properties/lineItems/items/properties/tracking/properties/isBilledTo`, it's missing: $.paths['/companies/{companyId}/data/bills'].get.responses['200'].content['application/json'].schema.allOf[0].properties.results.items.properties.lineItems.items.properties.tracking.properties.isBilledTo [3989:21]
```

when trying to iterate through this OpenAPI document https://github.com/codatio/oas/blob/main/yaml/Codat-Accounting.yaml

This is a document built by Stoplight (which can resolve these references) and while the referencing here is completely wild it is totally valid according to spec as far as I can tell.

The reference references a response object in another response that is itself a reference to a component but the path is expecting that reference to be resolved inline.

**Comment by daveshanley** [comment]
Ah, yes good old `~1` encoding. When I first discovered this, I thought it was some old DOS issue. Then I learned about the wonderful encoding. So then I tried to wire in all the edge-cases it could appear in. It looks like I missed one :)

Is this in `0.5x` or is this against the `0.6.0` branch in #83?

**Comment by TristanSpeakEasy** [comment]
This is in 0.5x

**Comment by daveshanley** [comment]
OK, I will add this fix to 0.6.0.

**Comment by daveshanley** [comment]
This is a slightly more prominent issue than I would like. After following the code, I know why it's breaking 1) there is a minor encoding bug, but more annoyingly... these references can ONLY be followed by a resolved spec. 

Which is no big deal because that is what the resolver is for. 

However, the resolver is destructive, it's used by `vacuum` to mimic stoplight's behavior. I can resolve the spec easily, but I have no idea what could happen to the underlying model built from the unresolved spec.

To solve this, the index must keep a copy of the undamaged node tree, which actually means loading the tree to memory twice.

This may double memory consumption.

**Comment by daveshanley** [comment]
@TristanSpeakEasy does this still exist after 013.0?

**Comment by TristanSpeakEasy** [comment]
@daveshanley yeah still exists:

```
ERROR   validation error: [line 3989] resolving-references - cannot resolve reference `#/paths/~1companies~1%7BcompanyId%7D~1data~1bills/get/responses/200/content/application~1json/schema/allOf/0/properties/results/items/properties/lineItems/items/properties/tracking/properties/isBilledTo`, it's missing: $.paths['/companies/{companyId}/data/bills'].get.responses['200'].content['application/json'].schema.allOf[0].properties.results.items.properties.lineItems.items.properties.tracking.properties.isBilledTo [3989:21] | $.paths['/companies/{companyId}/data/bills'].get.responses['200'].content['application/json'].schema.allOf[0].properties.results.items.properties.lineItems.items.properties.tracking.properties.isBilledTo
ERROR   validation error: [line 3989] resolving-references - component '#/paths/~1companies~1%7BcompanyId%7D~1data~1bills/get/responses/200/content/application~1json/schema/allOf/0/properties/results/items/properties/lineItems/items/properties/tracking/properties/isBilledTo' does not exist in the specification | $.paths['/companies/{companyId}/data/bills'].get.responses['200'].content['application/json'].schema.allOf[0].properties.results.it
[Codat-Accounting-Stoplight-References.zip](https://github.com/pb33f/libopenapi/files/13259504/Codat-Accounting-Stoplight-References.zip)
ems.properties.lineItems.items.properties.tracking.properties.isBilledTo
```

have attached the exact spec that was causing the issue (as Codat have since removed those references)

**Comment by daveshanley** [comment]
mmm. we're still going to need a resolved copy of the spec, which is how vaccum operates. still a duplication of memory, not a big deal, but still kinda a big deal. so this would have to be conditional I think.. somehow

**Comment by daveshanley** [comment]
I am leaning on `wontfix` on this one, the amount of work required to enable it, is significant, it's also a super bad design and even though its valid, I like the 'cannot resolve' error reporting back. I feel like vacuum should be able to catch these and warn you.

Thoughts?

**Comment by TristanSpeakEasy** [comment]
Yeah I'm happy with that I can just reference this issue, when we run into it again with customers and ask them to fix up the terrible references

**Comment by daveshanley** [comment]
wontfix: This is a limitation of the library in this use-case, while valid, these types of refs are just bad design and the library is taking a hard position on not being able to resolve them.
