### ISSUE TITLE
Line and column number incorrect on build schema error

### ISSUE THREAD

**Issue by TristanSpeakEasy** [pb33f/libopenapi#86]
https://github.com/pb33f/libopenapi/blob/cc5b7e73d9a0791329eb2e3e71ec90301ef63f92/datamodel/low/base/schema.go#L962 the column and line number are swapped around the wrong way on this error

**Comment by daveshanley** [comment]
Whoops. willfix in next bugsweep.

**Comment by daveshanley** [comment]
Fixed in `v0.6.1`
