### ISSUE TITLE
GetAllParametersFromOperations doesn't contain all parameters in document - v0.6.1

### ISSUE THREAD

**Issue by TristanSpeakEasy** [pb33f/libopenapi#88]
For this OpenAPI Document:

```yaml
openapi: 3.0.0
servers:
  - url: http://localhost:8080
paths:
  /test:
    get:
      parameters:
        - name: action
          in: query
          schema:
            type: string
        - name: action
          in: query
          schema:
            type: string
```

I would expect the index function `GetAllParametersFromOperations()` to return both parameters in the array of parameters it returns at the bottom of the tree.

Currently it seems to only have one of the parameters so our validation can't pick up on this and alert the user

**Comment by daveshanley** [comment]
Will pick up in the next bugsweep.

**Comment by daveshanley** [comment]
So after looking into this, it's the correct behavior. This sample has two conflicting params, both named `action` and both in `query`.

So the index only extracts one of them. However, it also adds a new `error` to `index.operationParamErrors` informing you of a duplication problem. Your validation code should use these errors.

Param errors can be extracted using `GetOperationParametersIndexErrors()`

The code is operating correctly, so this is a wont-fix.

**Comment by daveshanley** [comment]
I have added a test that showcases this behavior.
