### ISSUE TITLE
Feature: Make models fully mutable.

### ISSUE THREAD

**Issue by daveshanley** [pb33f/libopenapi#89]
libopenapi is currently optimized for reading. Writing was not an MVP priority. However, as we move forward, this use case is becoming more requested in various threads in chat.

So, let's make models fully editable, allowing easy high-level editing/adding/removing of objects and then being able to 're-render' the model (so all the line numbers and modifications all shift accordingly).

**Comment by daveshanley** [comment]
This has been implemented in `v0.7.0`

[Documentation and examples](https://pb33f.io/libopenapi/modifying/)

**Comment by juk80x** [comment]
Thank you for completing this work. It has unblocked some extremely important work for me.

**Comment by daveshanley** [comment]
> Thank you for completing this work. It has unblocked some extremely important work for me.

Thank you for your donation! I really appreciate it.
